name: 'Platform.sh Actions'
description: 'Perform action on platform.sh projects'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'server'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  action:
    description: 'Action to perform'
    required: true
    default: 'deploy'
  project-id:
    description: 'Project ID on platform.sh'
    required: true
  cli-token:
    description: 'Token for platform.sh CLI'
    required: true
  ssh-private-key:
    description: 'SSH key to access the git repository on platform.sh'
    required: false
  cli-version:
    description: 'Platform.sh CLI version to setup'
    required: true
    default: 'latest'
  force-push:
    description: 'Force push to Platform.sh'
    required: false
  environment-name:
    description: 'Name of the platform.sh instance'
    required: false
  parent-environment-name:
    description: 'Name of the platform.sh instance to branch from'
    required: false
# Define your outputs here.
outputs:
  deployed-url:
    description: 'URL of deployed instance'

runs:
  using: node24
  main: dist/index.js
